/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 .\work.glb
*/

import React, { Suspense } from "react";
import { useGLTF, OrthographicCamera, OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";

export function Model1(props) {
  const { nodes, materials } = useGLTF("/work.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-2.4, 48.53, 92.6]}>
          <mesh
            geometry={nodes.Cube.geometry}
            material={nodes.Cube.material}
            position={[0, -9.16, -0.26]}
          />
          <mesh
            geometry={nodes.Rectangle_2.geometry}
            material={nodes.Rectangle_2.material}
            position={[41.27, -9.19, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Rectangle_3.geometry}
            material={nodes.Rectangle_3.material}
            position={[-47.75, -9.19, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Shape.geometry}
            material={nodes.Shape.material}
            position={[-26.58, 58.19, -5.05]}
          />
        </group>
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={-100000}
          position={[55.59, 41.56, 997.59]}
          rotation={[-0.04, 0.06, 0]}
        />
        <directionalLight
          intensity={0.7}
          decay={2}
          position={[311.52, 276.53, 419.43]}
          rotation={[-0.58, 0.56, -0.67]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/work.gltf");
export default function WorkModel() {
  return (
    <div className="w-11 -mt-11 ">
      <Canvas>
        <ambientLight intensity={1} />
        <OrbitControls />
        <Suspense fallback={null}>
          <Model1 />
        </Suspense>
      </Canvas>
    </div>
  );
}
